config/routes.rb
Iforum::Application.routes.draw do |map|
  
  match 'login' => "users#login", :as => "login"
  match 'logout' => "users#logout", :as => "logout"
  match 'signup' => "users#new", :as => "signup"
  
  match 'feed'  => redirect("/feed.xml")
  
  match 'feed.:format' => "posts#feed", :as => "feed"
    
  resources :users

  resources :forums do
    resources :posts
  end
  
  resources :posts do
    resources :comments
  end
  
  resources :comments
  
  root :to => "forums#index"
  match ':controller(/:action(/:id(.:format)))'
  
  match '*anything', :to => redirect("/")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  
  validates_presence_of :content
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  validates_presence_of :name, :description
  validates_uniqueness_of :name
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content
  validates_length_of :title, :within => 2..30
  belongs_to :forum
  belongs_to :user
  has_many :comments
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  
  
  validates_presence_of :name
  validates_uniqueness_of :name
  attr_accessor :password_confrimation
  validates_confirmation_of :password
  
  def self.authenticate(name, password)
    user = self.find_by_name(name)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end
  
  def password
    @password
  end
  
  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end
  
  private
  
  def password_non_blank
    error.add(:password, "missing password") if hashed_password.blank?
  end
  
  def self.encrypted_password(password, salt)
    string_to_hash = password + "roamlog" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end
  
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end
  

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :check, :only => [:index]
  
  def index
    @posts = Post.all.paginate :page => params[:page], :per_page => 10
  end
  
  def login
    if request.post?
      user = User.authenticate(params[:name], params[:password])
      if user && user.isadmin
        session[:user_id] = user.id
        session[:name] = params[:name]
        redirect_to :action => "index"
      else
        flash.now[:notice] = "Invalid user/password"
      end
    end
  end
  
  def check
    user = User.find_by_id_and_isadmin(session[:user_id], true)
    unless user
      flash[:notice] = "Please login"
      session[:user_id] = nil
      session[:name] = nil
      redirect_to :controller => "admin", :action => "login"    
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  
  def find_user
    @user = User.find(session[:user_id])
  end
    
  protected
  
  def login_required
    unless User.find_by_id(session[:user_id])
      flash[:notice] = "Please login"
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_post, :only => [:create]
  before_filter :find_user
  
  def create
    @comment = @post.comments.build(params[:comment])
    @comment.user = @user
    
    if @comment.save
      redirect_to(post_path(@post))
    else
      redirect_to(post_path(@post))
    end
  end
  
  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end
  
  protected
  
  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  respond_to :html, :xml
  before_filter :find_forum, :except => [:index, :new, :create]
  before_filter :login_required, :except => [:index, :show, ]
  
  def index
    @forums = Forum.all.paginate :per_page => 10, :page => params[:page], :order => 'created_at DESC'
    respond_with @forums
  end
  
  def new
    @forum = Forum.new
    respond_with @forum
  end
  
  def show
    @posts = @forum.posts.paginate :page => params[:page], :per_page => 10, :order => "created_at DESC"
    respond_with @forum
  end
  
  def create
    @forum = Forum.new(params[:forum])
    flash[:notice] = "forum successfully created..." if @forum.save
    respond_with @forum
  end
  
  def edit
    respond_with @forum
  end
  
  def update
    flash[:notice] = "forum successfully updated..." if @forum.update_attributes(params[:post])
    respond_with @forum
  end
  
  def destroy
    @forum.destroy
    respond_with @forum
  end
  
  protected
  
  def find_forum
    @forum = Forum.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to :action => 'index'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :xml
  before_filter :find_forum, :except => [:edit, :show, :feed, :destroy]
  before_filter :find_post, :except => [:index, :new, :create, :feed]
  before_filter :login_required, :except => [:show, :index, :feed]
  
  def index
    redirect_to(forum_path(@forum))
  end
  
  def new
    @post = @forum.posts.build
  end
  
  def create
    @post = @forum.posts.build(params[:post])
    @user = User.find(session[:user_id])
    @post.user = @user
    if @post.save
      redirect_to(forum_posts_path(@forum))
    else
      render :action => "new"
    end
  end
  
  def edit
    @forum = @post.forum
  end
  
  def show
    @forum = @post.forum
  end
  
  def update
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was successfully updated..."
      redirect_to(forum_posts_path(@forum))
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @post.destroy
    
    redirect_to :controller => "admin", :action => "index"
  end
  
  def feed
    @posts = Post.limit(10).order("id DESC")
    respond_to do |format|
      format.xml { render :layout => false }
    end
  end
  
  protected
  
  def find_forum
    @forum = Forum.find(params[:forum_id])
  end
  
  def find_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to :controller => "forums", :action => 'index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :xml
  before_filter :login_required, :except => [:new, :create, :login, :logout]
  before_filter :find_user, :only => [:edit, :update, :destroy]
  before_filter :respond_user, :only => [:edit]
  
  def index
    @users = User.order("name")
    respond_with @users
  end

  def show
    redirect_to users_path
  end

  def new
    @user = User.new
    respond_with @user
  end

  def edit
  end

  def create
    @user = User.new(params[:user])
    flash[:notice] = "User was successfully created..." if @user.save
    respond_with @user
  end

  def update
    flash[:notice] = "User was successfully updated..." if @user.update_attributes(params[:user])
    respond_with @user
  end

  def destroy
    @user.destroy
    respond_with @user
  end
  
  def login
    if request.post?
      user = User.authenticate(params[:name], params[:password])
      if user
        session[:user_id] = user.id
        session[:name] = params[:name]
        redirect_to :controller => "forums", :action => "index"
      else
        flash.now[:notice] = "Invalid user/password"
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :controller => "forums", :action => "index"
  end
  
  protected
  
  def find_user
    @user = User.find(params[:id])
  end
  
  def respond_user
    respond_with @user
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def coderay(text)
    text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
      CodeRay.scan($3, $2).div(:css => :class)
    end  
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum admin", :controller => "admin", :action => "index" %> » admin
<% end -%>
<% content_for :nav_right do -%>
	<%= link_to "iForum", forums_path %>
<% end -%>

<% @posts.each do |post| %>
	<div class="post">
		<div class="main">
			<div class="main_wrap">
				» <%= post.title %>
			</div>
		</div>
		<div class="sub">
			<%= link_to "delete", post_path(post), :confirm => "are you sure?", :method => :delete %>
		</div>
	</div>
<% end %>
<div class="paginate">
	<%= will_paginate @posts, :previous_label => "«", :next_label => "»" %>	
</div>

app/views/admin/login.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum admin", :controller => "admin", :action => "index" %> » login
<% end -%>

<div class="form">
<%= form_tag do %>
  <div class="field">
  	<label for="name">Name:</label>
	<%= text_field_tag :name, params[:name] %>
  </div>

  <div class="field">
  	<label for="password">Password:</label>
    <%= password_field_tag :password, params[:password] %>
  </div>

  <div class="actions">
  	<%= submit_tag "login" %>
  </div>
<% end -%>
</div>

app/views/forums/_form.html.erb
<div class="form">
	<%= form_for @forum do |f| -%>
		<%= f.error_messages %>
		
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :description %>
			<%= f.text_field :description %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end -%>
</div>

app/views/forums/edit.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » edit forum
<% end -%>
<%= render :partial => 'form' %>

app/views/forums/index.html.erb
<% content_for :nav_left do -%>
	Discussion Forum
<% end -%>
<% content_for :nav_right do -%>
	<% unless session[:user_id] %>
		<%= link_to "login", login_path %>
	<% end %>
<% end -%>

<% @forums.each do |forum| %>
<div class="forum">
	<div class="main">
		<div class="short_main_wrap">
			『<%= link_to forum.name, forum %>』
		</div>
	</div>
	<div class="long_sub align_left">
		<%= forum.description %>
	</div>
</div>
<% end %>
<br>
<%= will_paginate(@forums, :previous_label => "«", :next_label => "»") %>

app/views/forums/new.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » new forum
<% end -%>
<%= render :partial => 'form' %>

app/views/forums/show.html.erb
<% content_for :nav_left do -%>
	<%= link_to "Discussion Forum", forums_path %> »  <%= @forum.name %>
<% end -%>
<% content_for :nav_right do -%>
	<%= link_to "new post", new_forum_post_path(@forum) %>
<% end -%>

<% @posts.each do |post| %>
<div class="post">
	<div class="main">
		<div class="main_wrap">
			» <%= link_to post.title, post_path(post) %>
		</div>
	</div>
	<div class="sub">
		200
	</div>
</div>
<% end %>
<div class="paginate">
	<%= will_paginate @posts, :previous_label => "«", :next_label => "»" %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>iForum</title>
	<%= stylesheet_link_tag "reset", "style", "coderay" %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
</head>
<body>
	<div id="page">
		<div id="header">
			<div class="main">
				<div class="main_wrap">
					<h2><%= yield :nav_left %></h2>
				</div>
			</div>
			<div class="sub">
				<%= yield :nav_right %>
			</div>
		</div>
		<div id="content">
			<div class="notice">
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
			</div>
			<%= yield %>
		</div>
		<div id="footer">
			<div class="main">
				<div class="short_main_wrap">
					© 2008 - 2010
				</div>
			</div>
			
			<div class="long_sub">
				<% if session[:user_id] %>
					logged in as: <%= session[:name] %> • <%= link_to "logout", logout_path %>
				<% else %>
					<%= link_to "signup", signup_path %>
				<% end %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="form">
	<%= form_for ([@forum, @post]) do |f| -%>
		<%= f.error_messages %>
		
		<div class="field">
			<%= f.label :title %>
			<%= f.text_field :title, :size => 50 %>
		</div>
		<div class="field">
			<%= f.label :content %>
			<%= f.text_area :content, :cols => 58, :rows => 10 %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end -%>
</div>

app/views/posts/edit.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » <%= link_to @forum.name, forum_path(@forum) %> » edit post
<% end -%>

<%= render :partial => 'form' %>

app/views/posts/new.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » <%= link_to @forum.name, forum_path(@forum) %> » new post
<% end -%>

<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<% content_for :nav_left do -%>
	» <%= @post.title %>
<% end -%>
<% content_for :nav_right do -%>
	<% if @post.user_id == session[:user_id] %>
		<%= link_to "edit", edit_post_path(@post) %>
	<% end %>
	<%= link_to "back", forum_path(@forum) %>
<% end -%>

<div class="post">
	<%= raw (coderay(@post.content)) %>
</div>

<% unless @post.comments.blank? %>
<div class="comment">
	<fieldset>
	
	<legend>Comments</legend>
	
	<% @post.comments.each do |comment| %>
		<div class="main">
			<div class="comment_wrap">
				<%= link_to "#", comment_path(comment) %>&nbsp;<%= comment.user.name %>
			</div>
		</div>
		<div class="comment_content">
			<%= comment.content %>
		</div>
		<div class="extra">
			»
		</div>
	<% end %>
	</fieldset>
</div>
<% end %>
<div class="form">
	<% if session[:user_id] %>
	<fieldset>
		<legend>Add comment</legend>
		
		<%= form_for [@post, @post.comments.build] do |f| -%>
			<%= f.error_messages %>
		
			<div class="field">
				<%= f.text_area :content, :cols => 58, :rows => 5 %>
			</div>
		
			<div class="actions">
				<%= f.submit %>
			</div>
		<% end -%>
	</fieldset>
	<% end %>
</div>

app/views/users/_form.html.erb
<div class="form">
<%= form_for(user) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
	<%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm" %>
	<%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » <%= link_to "User list", users_path %> » edit user
<% end -%>

<%= render :partial => 'form', :locals => {:user => @user} %>

app/views/users/index.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » <%= link_to "User list", users_path %>
<% end -%>
<% content_for :nav_right do -%>
	<%= link_to 'New user', new_user_path %>
<% end -%>

<div class="post">
	<div class="main">
		<div class="main_wrap">
			name
		</div>
	</div>
	<div class="sub">
		handle
	</div>
</div>
<% @users.each do |user| %>
  <div class="post">
	<div class="main">
    	<div class="main_wrap">
			<%= user.name %>
		</div>
	</div>
	<div class="sub">
    	<%= link_to 'Edit', edit_user_path(user) %>
    	<%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %>
	</div>
  </div>
<% end %>

app/views/users/login.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » login
<% end -%>

<div class="form">
<%= form_tag do %>
  <div class="field">
  	<label for="name">Name:</label>
	<%= text_field_tag :name, params[:name] %>
  </div>

  <div class="field">
  	<label for="password">Password:</label>
    <%= password_field_tag :password, params[:password] %>
  </div>

  <div class="actions">
  	<%= submit_tag "login" %>
  </div>
<% end -%>
</div>

app/views/users/new.html.erb
<% content_for :nav_left do -%>
	<%= link_to "iForum", forums_path %> » <%= link_to "User list", users_path %> »  <%= link_to "new user", signup_path %>
<% end -%>

<%= render :partial => 'form', :locals => {:user => @user} %>